version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels: ['type:chore', 'dependencies']
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/apps/api'
    schedule:
      interval: 'weekly'
      day: 'monday'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels: ['type:chore', 'dependencies', 'surface:api']
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/apps/web'
    schedule:
      interval: 'weekly'
      day: 'monday'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels: ['type:chore', 'dependencies', 'surface:web']
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/apps/mobile'
    schedule:
      interval: 'weekly'
      day: 'monday'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels: ['type:chore', 'dependencies', 'surface:mobile']
    open-pull-requests-limit: 5

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    labels: ['type:chore', 'dependencies', 'ci']
    open-pull-requests-limit: 5
