blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation Index
    url: https://github.com/htchen/app/tree/main/docs
    about: Review the living documentation before filing a new request.
defaults:
  assignees: []
  labels: []
