// Generated by generate-built-in-engine-closure.ts --write.
export const BUILT_IN_ENGINE_CLOSURE_MANIFEST_DIGEST =
  'sha256:8af44c6fe05d72be6adbac94cfa4bdb5ded27f24ac22d227550848f10dcaf148' as const;
