// Generated by generate-built-in-engine-closure.ts --write.
export const BUILT_IN_ENGINE_CLOSURE_MANIFEST_DIGEST =
  'sha256:42123bea3096c967bdde861d6f3d458e9d20584ee43b212ef61f4b09c8ee22e0' as const;
