// Generated by generate-built-in-engine-closure.ts --write.
export const BUILT_IN_ENGINE_CLOSURE_MANIFEST_DIGEST =
  'sha256:579af020b52bded5bf7ded98816af57840700b55293feca291e228882663a07b' as const;
