import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const PACKAGE_ROOT = path.resolve(import.meta.dirname, '..');
const MANIFEST_PATH = path.join(
  import.meta.dirname,
  'built-in-engine-closure.json',
);
const PIN_PATH = path.join(
  import.meta.dirname,
  'built-in-engine-closure-pin.ts',
);

const mode = process.argv[2] ?? '--check';
if (mode !== '--check' && mode !== '--write') {
  throw new Error(
    'Usage: generate-built-in-engine-closure.ts [--check|--write]',
  );
}

const files = [
  'package.json',
  ...listTypescriptFiles(path.join(PACKAGE_ROOT, 'src')),
]
  .map((relativePath) => manifestEntry(relativePath))
  .sort((left, right) =>
    left.path < right.path ? -1 : left.path > right.path ? 1 : 0,
  );
const manifest = {
  kind: 'built-in-engine-closure-manifest.v1' as const,
  entrypoint: 'src/cli.ts',
  scope: 'package-json-and-all-src-typescript' as const,
  files,
};
const manifestBytes = `${JSON.stringify(manifest, null, 2)}\n`;
const manifestDigest = digest(manifestBytes);
const pinSource = `// Generated by generate-built-in-engine-closure.ts --write.\nexport const BUILT_IN_ENGINE_CLOSURE_MANIFEST_DIGEST =\n  '${manifestDigest}' as const;\n`;

if (mode === '--write') {
  replaceFile(MANIFEST_PATH, manifestBytes);
  replaceFile(PIN_PATH, pinSource);
} else {
  assertCurrent(MANIFEST_PATH, manifestBytes);
  assertCurrent(PIN_PATH, pinSource);
}

function listTypescriptFiles(directory: string): string[] {
  const observed: string[] = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const absolute = path.join(directory, entry.name);
    if (entry.isSymbolicLink()) {
      throw new Error(`Built-in closure contains a symlink: ${absolute}`);
    }
    if (entry.isDirectory()) {
      observed.push(...listTypescriptFiles(absolute));
    } else if (entry.isFile() && entry.name.endsWith('.ts')) {
      observed.push(toPackageRelativePath(absolute));
    }
  }
  return observed;
}

function manifestEntry(
  relativePath: string,
  contentOverride?: string,
): {
  path: string;
  mode: '100644' | '100755';
  digest: `sha256:${string}`;
} {
  const absolute = path.join(PACKAGE_ROOT, ...relativePath.split('/'));
  const stats = fs.lstatSync(absolute);
  if (!stats.isFile() || stats.isSymbolicLink() || stats.nlink !== 1) {
    throw new Error(`Built-in closure file is unsafe: ${absolute}`);
  }
  const permissions = stats.mode & 0o777;
  if (permissions !== 0o644 && permissions !== 0o755) {
    throw new Error(`Built-in closure file mode is unsupported: ${absolute}`);
  }
  return {
    path: relativePath,
    mode: permissions === 0o755 ? '100755' : '100644',
    digest: digest(contentOverride ?? fs.readFileSync(absolute)),
  };
}

function toPackageRelativePath(absolute: string): string {
  const relative = path.relative(PACKAGE_ROOT, absolute);
  if (
    relative.length === 0 ||
    relative.startsWith('..') ||
    path.isAbsolute(relative)
  ) {
    throw new Error(`Built-in closure path escaped its package: ${absolute}`);
  }
  return relative.split(path.sep).join('/');
}

function digest(value: string | Buffer): `sha256:${string}` {
  return `sha256:${crypto.createHash('sha256').update(value).digest('hex')}`;
}

function replaceFile(filePath: string, content: string): void {
  const temporary = `${filePath}.${process.pid}.tmp`;
  fs.writeFileSync(temporary, content, { mode: 0o644 });
  fs.renameSync(temporary, filePath);
}

function assertCurrent(filePath: string, expected: string): void {
  const observed = fs.readFileSync(filePath, 'utf8');
  if (observed !== expected) {
    throw new Error(
      `Built-in engine closure metadata is stale; run ${path.basename(import.meta.filename)} --write.`,
    );
  }
}
