import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

import {
  resolveWorkspaceSourceClosure,
  type WorkspaceSourcePackage,
} from './workspace-source-closure.ts';

const DEFAULT_REPOSITORY_ROOT = path.resolve(import.meta.dirname, '../../..');
const MANIFEST_RELATIVE_PATH =
  'packages/workflow-engine/bootstrap/built-in-engine-closure.json';
const PIN_RELATIVE_PATH =
  'packages/workflow-engine/bootstrap/built-in-engine-closure-pin.ts';

export type BuiltInEngineClosureGenerationMode = '--check' | '--write';

export type BuiltInEngineClosureRender = Readonly<{
  manifest: Readonly<{
    kind: 'built-in-engine-closure-manifest.v2';
    entrypoint: 'src/cli.ts';
    scope: 'workspace-runtime-source-closure';
    packages: readonly WorkspaceSourcePackage[];
    files: readonly Readonly<{
      path: string;
      mode: '100644' | '100755';
      digest: `sha256:${string}`;
    }>[];
  }>;
  manifestBytes: string;
  manifestDigest: `sha256:${string}`;
  pinSource: string;
}>;

/** Render the exact built-in closure artifacts without mutating the repository. */
export function renderBuiltInEngineClosure(
  repositoryRoot: string,
): BuiltInEngineClosureRender {
  const root = fs.realpathSync(repositoryRoot);
  const packages = resolveWorkspaceSourceClosure(root);
  const files = packages
    .flatMap((descriptor) => {
      const packageRoot = requireContainedDirectory(
        root,
        descriptor.sourceRoot.split('/'),
      );
      const sourceRoot = requireContainedDirectory(packageRoot, ['src']);
      return [
        'package.json',
        ...listTypescriptFiles(packageRoot, sourceRoot),
      ].map((relativePath) =>
        manifestEntry(packageRoot, descriptor, relativePath),
      );
    })
    .sort((left, right) =>
      left.path < right.path ? -1 : left.path > right.path ? 1 : 0,
    );
  const manifest = Object.freeze({
    kind: 'built-in-engine-closure-manifest.v2' as const,
    entrypoint: 'src/cli.ts' as const,
    scope: 'workspace-runtime-source-closure' as const,
    packages,
    files: Object.freeze(files.map((entry) => Object.freeze(entry))),
  });
  const manifestBytes = `${JSON.stringify(manifest, null, 2)}\n`;
  const manifestDigest = digest(manifestBytes);
  const pinSource = `// Generated by generate-built-in-engine-closure.ts --write.\nexport const BUILT_IN_ENGINE_CLOSURE_MANIFEST_DIGEST =\n  '${manifestDigest}' as const;\n`;
  return Object.freeze({
    manifest,
    manifestBytes,
    manifestDigest,
    pinSource,
  });
}

/** Write or verify the rendered artifacts under one explicit repository root. */
export function generateBuiltInEngineClosure(
  repositoryRoot: string,
  mode: BuiltInEngineClosureGenerationMode,
): BuiltInEngineClosureRender {
  assertMode(mode);
  const root = fs.realpathSync(repositoryRoot);
  requireContainedDirectory(root, ['packages', 'workflow-engine', 'bootstrap']);
  const rendered = renderBuiltInEngineClosure(root);
  const manifestPath = path.join(root, MANIFEST_RELATIVE_PATH);
  const pinPath = path.join(root, PIN_RELATIVE_PATH);
  if (mode === '--write') {
    replaceFile(manifestPath, rendered.manifestBytes);
    replaceFile(pinPath, rendered.pinSource);
  } else {
    assertCurrent(manifestPath, rendered.manifestBytes);
    assertCurrent(pinPath, rendered.pinSource);
  }
  return rendered;
}

function listTypescriptFiles(packageRoot: string, directory: string): string[] {
  const observed: string[] = [];
  for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
    const absolute = path.join(directory, entry.name);
    if (entry.isSymbolicLink()) {
      throw new Error(`Built-in closure contains a symlink: ${absolute}`);
    }
    if (entry.isDirectory()) {
      observed.push(...listTypescriptFiles(packageRoot, absolute));
    } else if (entry.isFile() && entry.name.endsWith('.ts')) {
      observed.push(toPackageRelativePath(packageRoot, absolute));
    }
  }
  return observed;
}

function manifestEntry(
  packageRoot: string,
  descriptor: WorkspaceSourcePackage,
  relativePath: string,
  contentOverride?: string,
): {
  path: string;
  mode: '100644' | '100755';
  digest: `sha256:${string}`;
} {
  const absolute = path.join(packageRoot, ...relativePath.split('/'));
  const stats = fs.lstatSync(absolute);
  if (!stats.isFile() || stats.isSymbolicLink() || stats.nlink !== 1) {
    throw new Error(`Built-in closure file is unsafe: ${absolute}`);
  }
  const permissions = stats.mode & 0o777;
  if (permissions !== 0o644 && permissions !== 0o755) {
    throw new Error(`Built-in closure file mode is unsupported: ${absolute}`);
  }
  return {
    path:
      descriptor.closureRoot === '.'
        ? relativePath
        : path.posix.join(descriptor.closureRoot, relativePath),
    mode: permissions === 0o755 ? '100755' : '100644',
    digest: digest(contentOverride ?? fs.readFileSync(absolute)),
  };
}

function toPackageRelativePath(packageRoot: string, absolute: string): string {
  const relative = path.relative(packageRoot, absolute);
  if (
    relative.length === 0 ||
    relative.startsWith('..') ||
    path.isAbsolute(relative)
  ) {
    throw new Error(`Built-in closure path escaped its package: ${absolute}`);
  }
  return relative.split(path.sep).join('/');
}

function digest(value: string | Buffer): `sha256:${string}` {
  return `sha256:${crypto.createHash('sha256').update(value).digest('hex')}`;
}

function replaceFile(filePath: string, content: string): void {
  const temporary = `${filePath}.${process.pid}.tmp`;
  const observed = fs.lstatSync(filePath, { throwIfNoEntry: false });
  if (
    observed !== undefined &&
    (!observed.isFile() || observed.isSymbolicLink() || observed.nlink !== 1)
  ) {
    throw new Error(`Built-in closure output is unsafe: ${filePath}`);
  }
  if (fs.lstatSync(temporary, { throwIfNoEntry: false }) !== undefined) {
    throw new Error(
      `Built-in closure temporary path is occupied: ${temporary}`,
    );
  }
  try {
    fs.writeFileSync(temporary, content, { flag: 'wx', mode: 0o644 });
    fs.chmodSync(temporary, 0o644);
    fs.renameSync(temporary, filePath);
    fs.chmodSync(filePath, 0o644);
  } finally {
    fs.rmSync(temporary, { force: true });
  }
}

function assertCurrent(filePath: string, expected: string): void {
  const stats = fs.lstatSync(filePath, { throwIfNoEntry: false });
  const observed =
    stats?.isFile() && !stats.isSymbolicLink() && stats.nlink === 1
      ? fs.readFileSync(filePath, 'utf8')
      : null;
  if (
    observed !== expected ||
    stats === undefined ||
    (stats.mode & 0o777) !== 0o644
  ) {
    throw new Error(
      `Built-in engine closure metadata is stale; run ${path.basename(import.meta.filename)} --write.`,
    );
  }
}

function requireContainedDirectory(root: string, segments: string[]): string {
  let current = root;
  for (const segment of segments) {
    current = path.join(current, segment);
    const stats = fs.lstatSync(current, { throwIfNoEntry: false });
    if (
      stats === undefined ||
      !stats.isDirectory() ||
      stats.isSymbolicLink() ||
      fs.realpathSync(current) !== current
    ) {
      throw new Error(`Built-in closure directory is unsafe: ${current}`);
    }
  }
  return current;
}

function assertMode(
  mode: string,
): asserts mode is BuiltInEngineClosureGenerationMode {
  if (mode !== '--check' && mode !== '--write') {
    throw new Error(
      'Usage: generate-built-in-engine-closure.ts [--check|--write]',
    );
  }
}

if (import.meta.main) {
  const mode = process.argv[2] ?? '--check';
  assertMode(mode);
  generateBuiltInEngineClosure(DEFAULT_REPOSITORY_ROOT, mode);
}
