/** Generated by generate-harness-bootstrap-runtime.ts. */
export const HARNESS_BOOTSTRAP_RUNTIME_CLOSURE_MANIFEST_DIGEST =
  'sha256:845819cf01339860ed020ba8cf61b621ca0c2e0cab37d55309c48beb11b4804d' as const;
