/** Generated by generate-harness-bootstrap-runtime.ts. */
export const HARNESS_BOOTSTRAP_RUNTIME_CLOSURE_MANIFEST_DIGEST =
  'sha256:efa3097fb030e27c009ad0f86498eb7c79086f28c3e8aac13008237712b87686' as const;
