/** Generated by generate-harness-bootstrap-runtime.ts. */
export const HARNESS_BOOTSTRAP_RUNTIME_CLOSURE_MANIFEST_DIGEST =
  'sha256:a37c78e37d0361218df0cfdb6326be984412f5238dd6c7368195e1317611327e' as const;
