name: Prettier Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        with:
          version: 11.12.0

      - uses: actions/setup-node@v7.0.0
        with:
          node-version: 22.22.1
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Prettier check
        run: pnpm run format:check
