/**
 * Generated by scripts/generate-workflow-test-shards.ts.
 * Do not edit by hand; the tracked manifest owns this static import list.
 */
import '../task-diff-review-store.contract.test.ts';
import '../task-diff-review-lineage-supersession.contract.test.ts';
import '../task-strategy-correction-provider-lifecycle.integration.test.ts';
import '../full-gate-runner.integration.test.ts';
import '../authority-audit-ledger.contract.test.ts';
import '../evidence-node.contract.test.ts';
import '../external-effect-cli.contract.test.ts';
import '../provider-retry-accounting.contract.test.ts';
import '../class-disposition-mounting.integration.test.ts';
import '../declared-path-symbol-floor.integration.test.ts';
import '../floor-trimming.integration.test.ts';
import '../legacy-provider-invocation-projection.integration.test.ts';
import '../open-task-atomic-ingress.integration.test.ts';
import '../provider-retention.contract.test.ts';
import '../amend-plan-change-option.integration.test.ts';
import '../amend-plan-state-gate.integration.test.ts';
import '../control-plane-successive-promotion-production.integration.test.ts';
import '../intervention-sidecar-workflow-binding.integration.test.ts';
import '../semantic-ledger-propose.integration.test.ts';
import '../completion.integration.test.ts';
import '../issues.integration.test.ts';
import '../intervention-local-adoption-launcher.integration.test.ts';
import '../publish-executor.integration.test.ts';
import '../investigation-scanner.integration.test.ts';
import '../legacy-plan-migration.integration.test.ts';
import '../workflow-guidance.integration.test.ts';
