/**
 * Generated by scripts/generate-workflow-test-shards.ts.
 * Do not edit by hand; the tracked manifest owns this static import list.
 */
import '../evidence-reuse-path.contract.test.ts';
import '../task-diff-review-external-inventory.contract.test.ts';
import '../task-diff-review-store.contract.test.ts';
import '../task-diff-review-provider-output.contract.test.ts';
import '../task-diff-review-provider-role.contract.test.ts';
import '../check-registry-port.contract.test.ts';
import '../spec-scenario-preservation.contract.test.ts';
import '../authority-audit-ledger.contract.test.ts';
import '../execution-core-terminal-failures.contract.test.ts';
import '../intervention-control-bootstrap.contract.test.ts';
import '../intervention-control-cli.contract.test.ts';
import '../maintainer-manifest.contract.test.ts';
import '../plan-review.contract.test.ts';
import '../amend-plan-trailers.contract.test.ts';
import '../legacy-provider-policy-lineage-gap.integration.test.ts';
import '../unified-cli-routing.contract.test.ts';
import '../class-sample-audit-duplicate.integration.test.ts';
import '../control-plane-promotion-material-binding.integration.test.ts';
import '../control-plane-refusal-audit.integration.test.ts';
import '../recovery-quarantine.integration.test.ts';
import '../contract-artifact-digests.test.ts';
import '../task-strategy-execution.integration.test.ts';
import '../generated/package-tests/core/job-attempt-runtime.contract.test.ts';
import '../generated/package-tests/core/repository-path.contract.test.ts';
