/**
 * Generated by scripts/generate-workflow-test-shards.ts.
 * Do not edit by hand; the tracked manifest owns this static import list.
 */
import '../archive-diagnostic-preservation.contract.test.ts';
import '../assurance-assessment-chain.contract.test.ts';
import '../single-pass-finalize-command.integration.test.ts';
import '../finalize-authenticated-gate-recovery.integration.test.ts';
import '../task-diff-review-artifact.contract.test.ts';
import '../full-gate-telemetry-summary.contract.test.ts';
import '../spec-scenario-preservation.contract.test.ts';
import '../execution-governance.contract.test.ts';
import '../external-effect-refusal-audit.contract.test.ts';
import '../intervention-control-persistence.contract.test.ts';
import '../intervention-adoption-grant-renewal.integration.test.ts';
import '../maintainer-candidate-artifacts.contract.test.ts';
import '../maintainer-grant-v2.contract.test.ts';
import '../retention-control.contract.test.ts';
import '../semantic-reuse-reporting.integration.test.ts';
import '../adaptive-class-sample-gate.integration.test.ts';
import '../archive-diagnostic-budget.integration.test.ts';
import '../class-sample-audit-duplicate.integration.test.ts';
import '../control-plane-initial-supervisor-bootstrap.integration.test.ts';
import '../epoch-carry-forward-manifest.integration.test.ts';
import '../intervention-parent-pause-fence.integration.test.ts';
import '../maintainer-evidence-waiver-security.integration.test.ts';
import '../recovery-trust-root-restore.integration.test.ts';
import '../spec-delta-shared-applicability.integration.test.ts';
import '../spec-delta-transition-enforcement.integration.test.ts';
import '../contracts.test.ts';
import '../atomic-text.test.ts';
import '../collaboration-grant.integration.test.ts';
import '../contract-artifact-digests.test.ts';
import '../intervention-control-updater-cli.integration.test.ts';
import '../managed-trailers.contract.test.ts';
import '../ci.integration.test.ts';
import '../managed-change-contract.integration.test.ts';
import '../session.integration.test.ts';
