/**
 * Generated by scripts/generate-workflow-test-shards.ts.
 * Do not edit by hand; the tracked manifest owns this static import list.
 */
import '../contracts.test.ts';
import '../session.integration.test.ts';
import '../single-pass-finalize-command.integration.test.ts';
import '../finalize-authenticated-gate-recovery.integration.test.ts';
import '../git-security.test.ts';
import '../execution-governance.contract.test.ts';
import '../external-effect-refusal-audit.contract.test.ts';
import '../intervention-adoption-grant-renewal.integration.test.ts';
import '../maintainer-grant-v2.contract.test.ts';
import '../maintainer-grant-v2-reissue-cli.integration.test.ts';
import '../retention-control.contract.test.ts';
import '../semantic-reuse-reporting.integration.test.ts';
import '../adaptive-class-sample-gate.integration.test.ts';
import '../control-plane-initial-supervisor-bootstrap.integration.test.ts';
import '../control-plane-supervisor-history-crash.integration.test.ts';
import '../epoch-transition-retention-maintenance.integration.test.ts';
import '../intervention-parent-pause-fence.integration.test.ts';
import '../maintainer-evidence-waiver-security.integration.test.ts';
import '../recovery-authority-descriptor.integration.test.ts';
import '../recovery-trust-root-restore.integration.test.ts';
import '../spec-delta-transition-enforcement.integration.test.ts';
import '../collaboration-grant.integration.test.ts';
import '../issues.integration.test.ts';
import '../intervention-control-updater-cli.integration.test.ts';
import '../ci.integration.test.ts';
import '../managed-change-contract.integration.test.ts';
import '../generated/package-tests/agent-runtime/harness-jsonl-v1.contract.test.ts';
