/**
 * Generated by scripts/generate-workflow-test-shards.ts.
 * Do not edit by hand; the tracked manifest owns this static import list.
 */
import '../semantic-reconciliation.contract.test.ts';
import '../task-strategy-correction-round-store.contract.test.ts';
import '../task-strategy-local-correction-round.integration.test.ts';
import '../task-strategy-caller-correction.integration.test.ts';
import '../task-diff-review.contract.test.ts';
import '../task-diff-review-public-continuation.integration.test.ts';
import '../task-strategy-correction-provider-contract.test.ts';
import '../full-gate-progress.contract.test.ts';
import '../full-gate-reporter.contract.test.ts';
import '../assurance-inspection.integration.test.ts';
import '../change-class-floors.contract.test.ts';
import '../check-registry-package-boundaries.contract.test.ts';
import '../authority-audit-cli.contract.test.ts';
import '../authority-audit-profile.contract.test.ts';
import '../protected-capability-path-roles.contract.test.ts';
import '../amend-plan-reopen.contract.test.ts';
import '../legacy-provider-output-schema-projection.integration.test.ts';
import '../plan-amendment-contribution.integration.test.ts';
import '../provider-retention-closure.integration.test.ts';
import '../task-mandate.contract.test.ts';
import '../assurance-floor-propose.integration.test.ts';
import '../control-plane-v2-sidecar-pin.integration.test.ts';
import '../planning-r6-review-coverage.integration.test.ts';
import '../spec-delta-shared-applicability.integration.test.ts';
import '../workspace-source-closure.contract.test.ts';
import '../ci-planning.integration.test.ts';
import '../document-refresh.integration.test.ts';
import '../intervention-control-bootstrap-cli.integration.test.ts';
import '../ci-bootstrap.integration.test.ts';
import '../ai-adapter-evaluation.integration.test.ts';
import '../provider-automatic-retry.integration.test.ts';
import '../investigation-session.integration.test.ts';
import '../workflow-rehearsal.integration.test.ts';
import '../generated/package-tests/agent-runtime/bounded-provider-process.integration.test.ts';
import '../generated/package-tests/core/check-command.contract.test.ts';
import '../generated/package-tests/core/tracked-object-reader-port.contract.test.ts';
