/**
 * Generated by scripts/generate-workflow-test-shards.ts.
 * Do not edit by hand; the tracked manifest owns this static import list.
 */
import '../assurance-assessment-chain.contract.test.ts';
import '../declared-path-symbols.contract.test.ts';
import '../task-strategy-red-revision-store.contract.test.ts';
import '../task-strategy-store.contract.test.ts';
import '../task-diff-review-external-input.contract.test.ts';
import '../task-diff-review-external-continuation.integration.test.ts';
import '../class-sample-audit.contract.test.ts';
import '../hit-predicate.contract.test.ts';
import '../path-role-registry.contract.test.ts';
import '../openspec-adapter.integration.test.ts';
import '../openspec-planning-assets.integration.test.ts';
import '../maintainer-attestation.integration.test.ts';
import '../execution-replacement.integration.test.ts';
import '../external-effect-grant.contract.test.ts';
import '../external-effect-optional-ttl.contract.test.ts';
import '../investigation-groups.contract.test.ts';
import '../intervention-control.contract.test.ts';
import '../provider-async-process.contract.test.ts';
import '../execution-replacement-crash-window.integration.test.ts';
import '../propose-planning-workspace.integration.test.ts';
import '../archive-applicability-public-projection.integration.test.ts';
import '../control-plane-successive-promotion-lineage.integration.test.ts';
import '../intervention-sidecar-session.integration.test.ts';
import '../maintainer-evidence-waiver.integration.test.ts';
import '../provider-lease-expiry-retry.integration.test.ts';
import '../recovery-authority-cli.integration.test.ts';
import '../recovery-trust-root-restore-cli.integration.test.ts';
import '../archive-transformation.integration.test.ts';
import '../ci-archive.integration.test.ts';
import '../finalize-transaction-recovery.integration.test.ts';
import '../handoff.integration.test.ts';
import '../provider-adapters.integration.test.ts';
import '../investigation-why.integration.test.ts';
import '../task-mechanical-transform-lifecycle.integration.test.ts';
import '../generated/package-tests/core/canonical-json.contract.test.ts';
import '../generated/package-tests/fixture-adapter/fixture-check-registry.integration.test.ts';
import '../generated/package-tests/grants/grant-lifecycle.contract.test.ts';
