/**
 * Generated by scripts/generate-workflow-test-shards.ts.
 * Do not edit by hand; the tracked manifest owns this static import list.
 */
import '../declared-path-symbols.contract.test.ts';
import '../review-enforcement.contract.test.ts';
import '../semantic-manifest-reuse.integration.test.ts';
import '../evidence-reuse-path.contract.test.ts';
import '../task-strategy-correction-round-store.contract.test.ts';
import '../task-strategy-local-correction-round.integration.test.ts';
import '../task-strategy-caller-correction.integration.test.ts';
import '../task-diff-review-external-store.contract.test.ts';
import '../task-diff-review-public-continuation.integration.test.ts';
import '../task-strategy-correction-provider-contract.test.ts';
import '../authority-relay-command.contract.test.ts';
import '../authority-audit-cli.contract.test.ts';
import '../authority-audit-profile.contract.test.ts';
import '../execution-core.contract.test.ts';
import '../execution-core-terminal-failures.contract.test.ts';
import '../maintainer-grant-v2-reissue-cli.integration.test.ts';
import '../protected-capability-path-roles.contract.test.ts';
import '../legacy-provider-output-schema-projection.integration.test.ts';
import '../plan-amendment-contribution.integration.test.ts';
import '../provider-retention-closure.integration.test.ts';
import '../task-mandate.contract.test.ts';
import '../assurance-floor-propose.integration.test.ts';
import '../control-plane-supervisor-history-crash.integration.test.ts';
import '../control-plane-v2-sidecar-pin.integration.test.ts';
import '../planning-r6-review-coverage.integration.test.ts';
import '../ci-planning.integration.test.ts';
import '../document-refresh.integration.test.ts';
import '../intervention-control-bootstrap-cli.integration.test.ts';
import '../ci-bootstrap.integration.test.ts';
import '../ai-adapter-evaluation.integration.test.ts';
import '../provider-automatic-retry.integration.test.ts';
import '../investigation-session.integration.test.ts';
import '../plan-review.integration.test.ts';
import '../workflow-rehearsal.integration.test.ts';
