/**
 * Generated by scripts/generate-workflow-test-shards.ts.
 * Do not edit by hand; the tracked manifest owns this static import list.
 */
import '../implementation-reconciliation-finalization.integration.test.ts';
import '../finalize-recovery-command.integration.test.ts';
import '../task-diff-review.contract.test.ts';
import '../task-diff-review-external-inventory.contract.test.ts';
import '../task-diff-review-status-read-only.integration.test.ts';
import '../task-diff-review-provider-output.contract.test.ts';
import '../task-strategy-provider-retry.integration.test.ts';
import '../class-sample-audit.contract.test.ts';
import '../hit-predicate.contract.test.ts';
import '../scan-hit-context-window.contract.test.ts';
import '../assurance-inspection.integration.test.ts';
import '../git-security.test.ts';
import '../planning-transition.contract.test.ts';
import '../authority-attestation.contract.test.ts';
import '../evidence-currentness.contract.test.ts';
import '../engine-projection-authority.integration.test.ts';
import '../execution-grant-mandate-audit.contract.test.ts';
import '../execution-store.contract.test.ts';
import '../investigation-groups.contract.test.ts';
import '../plan-review.contract.test.ts';
import '../investigation-branch-rename.integration.test.ts';
import '../legacy-provider-attempt-numbering.integration.test.ts';
import '../provider-runtime-registration.integration.test.ts';
import '../control-plane-recovery-grant.integration.test.ts';
import '../planning-shadow-metrics.integration.test.ts';
import '../archive-transition.integration.test.ts';
import '../execution-runtime.integration.test.ts';
import '../harness-bootstrap-human-ux.integration.test.ts';
import '../guard-contract.integration.test.ts';
import '../hooks.integration.test.ts';
import '../planning-transition.integration.test.ts';
import '../managed-change-lifecycle.integration.test.ts';
import '../session-check-invalidation.integration.test.ts';
import '../task-mechanical-transform.integration.test.ts';
