/**
 * Generated by scripts/generate-workflow-test-shards.ts.
 * Do not edit by hand; the tracked manifest owns this static import list.
 */
import '../propose-scan-saturation-acceptance.integration.test.ts';
import '../evidence-reuse-production.integration.test.ts';
import '../task-diff-review-direct-human-resume.integration.test.ts';
import '../task-diff-review-correction-head.integration.test.ts';
import '../task-diff-review-provider-worker.integration.test.ts';
import '../collaboration-grant-selection.contract.test.ts';
import '../openspec-schema-contract.integration.test.ts';
import '../authority-refusal-audit.contract.test.ts';
import '../external-effect-reconciliation.contract.test.ts';
import '../maintainer-post-approval-budget.integration.test.ts';
import '../provider-invocation-supersession.contract.test.ts';
import '../protected-capabilities.contract.test.ts';
import '../planning-workspace.integration.test.ts';
import '../task-mandate-grant-budget.integration.test.ts';
import '../control-plane-promotion-producer.integration.test.ts';
import '../execution-workflow-blocker-projection.integration.test.ts';
import '../provider-semantic-contract-rollover.integration.test.ts';
import '../recovery-authority-descriptor.integration.test.ts';
import '../archive-eligibility.integration.test.ts';
import '../intervention-control-updater.integration.test.ts';
import '../maintainer-mode.integration.test.ts';
import '../provider-worker.integration.test.ts';
import '../ignored-state.integration.test.ts';
import '../investigation-why.integration.test.ts';
import '../runner.integration.test.ts';
import '../task-revision-lease.integration.test.ts';
