/**
 * Generated by scripts/generate-workflow-test-shards.ts.
 * Do not edit by hand; the tracked manifest owns this static import list.
 */
import '../archive-applicability-provenance.contract.test.ts';
import '../scan-saturation-exit.integration.test.ts';
import '../implementation-reconciliation-finalization.integration.test.ts';
import '../finalize-recovery-command.integration.test.ts';
import '../task-diff-review-external-store.contract.test.ts';
import '../task-diff-review-status-read-only.integration.test.ts';
import '../task-strategy-provider-retry.integration.test.ts';
import '../planning-transition.contract.test.ts';
import '../authority-attestation.contract.test.ts';
import '../authority-relay-command.contract.test.ts';
import '../evidence-node.contract.test.ts';
import '../evidence-currentness.contract.test.ts';
import '../engine-projection-authority.integration.test.ts';
import '../execution-grant-mandate-audit.contract.test.ts';
import '../execution-store.contract.test.ts';
import '../agent-role-plan.contract.test.ts';
import '../investigation-branch-rename.integration.test.ts';
import '../legacy-provider-attempt-numbering.integration.test.ts';
import '../planning-execution-epoch-recovery.integration.test.ts';
import '../provider-runtime-registration.integration.test.ts';
import '../control-plane-recovery-grant.integration.test.ts';
import '../planning-shadow-metrics.integration.test.ts';
import '../provider-semantic-contract-rollover.integration.test.ts';
import '../unified-plan-capability-path-roles.contract.test.ts';
import '../archive-transition.integration.test.ts';
import '../atomic-text.test.ts';
import '../execution-runtime.integration.test.ts';
import '../harness-bootstrap-human-ux.integration.test.ts';
import '../guard-contract.integration.test.ts';
import '../hooks.integration.test.ts';
import '../managed-trailers.contract.test.ts';
import '../plan-review.integration.test.ts';
import '../planning-transition.integration.test.ts';
import '../managed-change-lifecycle.integration.test.ts';
import '../session-check-invalidation.integration.test.ts';
import '../task-mechanical-transform.integration.test.ts';
import '../generated/package-tests/fixture-adapter/fixture-tracked-object-reader.integration.test.ts';
