/**
 * Generated by scripts/generate-workflow-test-shards.ts.
 * Do not edit by hand; the tracked manifest owns this static import list.
 */
import '../archive-applicability-provenance.contract.test.ts';
import '../semantic-reconciliation.contract.test.ts';
import '../task-strategy-red-revision-store.contract.test.ts';
import '../task-strategy-correction-store.contract.test.ts';
import '../task-diff-review-lineage.contract.test.ts';
import '../task-diff-review-provider-role.contract.test.ts';
import '../task-strategy-provider-contract.test.ts';
import '../full-gate-progress.contract.test.ts';
import '../spec-delta-applicability.contract.test.ts';
import '../intervention-control-bootstrap.contract.test.ts';
import '../intervention-control-cli.contract.test.ts';
import '../maintainer-manifest.contract.test.ts';
import '../amend-plan-reopen.contract.test.ts';
import '../legacy-provider-policy-lineage-gap.integration.test.ts';
import '../planning-execution-epoch-recovery.integration.test.ts';
import '../unified-cli-routing.contract.test.ts';
import '../control-plane-refusal-audit.integration.test.ts';
import '../recovery-quarantine.integration.test.ts';
import '../task-strategy-execution.integration.test.ts';
